Repository serokell/universum, pull requests merged in 2018-10, with the labels that each got.

#202 Added a pull request template
  .github/pull_request_template.md
Labels: type:not-code

#200 [#186] Implemented hClose and withFile
  CHANGES.md
  src/Universum/Base.hs
  src/Universum/Lifted/File.hs
Labels: type:feature

#195 [#204] Improve traces
  CHANGES.md
  src/Universum/Debug.hs
Labels: type:breaking

#197 Added hPutStr and hPutStrLn to the Print module
  CHANGES.md
  src/Universum/Print.hs
  src/Universum/Print/Internal.hs
  universum.cabal
Labels: type:breaking

#201 Generalize the type of `die`
  CHANGES.md
  src/Universum/Lifted/Env.hs
Labels: type:breaking

#203 Make `error` print callstack of its call site rather than its definition
  CHANGES.md
  src/Universum/Debug.hs
Labels: type:fix
