Repository serokell/universum, pull requests merged in 2018-02, with the labels that each got.

#140 [#129] Reexport id
  CHANGES.md
  README.md
  src/Universum/Function.hs
Labels: reexport needed

#141 [#128] Add Unsafe module
  CHANGES.md
  README.md
  src/Universum/Unsafe.hs
  universum.cabal
Labels: reexport needed

#143 [#130] Merge 'ToList' and 'Container', [#118] Export 'Type'
  CHANGES.md
  src/Universum/Base.hs
  src/Universum/Container/Class.hs
  src/Universum/Exception.hs
  universum.cabal
Labels: reexport needed, refactoring

#153 [#152] Use gauge instead of criterion, clean dependencies
  benchmark/Main.hs
  stack-7.10.3.yaml
  universum.cabal
Labels: refactoring, tests & benchmarks

#154 Compat wit ghc-8.4.1-rc1
  src/Universum/Debug.hs
Labels: bug-fix
